version: '3.1'

services:
    db:
        image: postgres:alpine
        restart: always
        environment: 
         POSTGRES_DB: empresa
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin
        ports:
         - "5432:5432"
        volumes:
         - postgresql-volume:/var/lib/postgresql/data
        networks:
         - postgresql
    
    pgadmin4:
        image: "dpage/pgadmin4"
        restart: always
        environment: 
         PGADMIN_DEFAULT_EMAIL: "juancamiloacevedoospina@gmail.com"
         PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
         - "5533:80"
        depends_on:
         - db
        networks:
         - postgresql
networks:
        postgresql:
                driver: bridge
volumes: 
  postgresql-volume:
    external: true