version: 2.1

jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
        docker-compose up -d

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
